### ISSUE TITLE
Replace voltmeter/ohmmeter images

### ISSUE THREAD

**Issue by rbwatson** [rbwatson/GoBabyGo#47]
Update images to show:
* Ohms - open circuit
* Ohms - continuity
* Volts - open circuit
* Volts - 6v battery voltage

**Comment by docsbydesign** [comment]
I found these, so far
* ![Ohms - continuity](https://user-images.githubusercontent.com/10519201/46374051-be31e800-c65d-11e8-86cd-e39b51af1783.jpg "Ohms - Continuity")
* ![Ohms - Open circuit](https://user-images.githubusercontent.com/10519201/46374056-bffbab80-c65d-11e8-9641-a9b27413efd6.jpg "Ohms - Open Circuit")

**Comment by rbwatson** [comment]
Also create/update the "ohms" setting image with the annotation.
