### ISSUE TITLE
Missing video & image links for "fit car to child" section

### ISSUE THREAD

**Issue by EvanBG42** [rbwatson/GoBabyGo#50]
[Masterati Tasks Page](https://merceru-tco.github.io/GoBabyGo/pages/cars-maserati-tasks.html)

The "fit car to child" section links to several missing images and videos on a Google Drive. Videos should be found, uploaded to the Mercer TCO Youtube page, and the links updated.

**Comment by rbwatson** [comment]
@rbwatson to upload videos and add links to this issue

**Comment by docsbydesign** [comment]
https://www.youtube.com/playlist?list=PL497S23eeZrFvNm3dY3I3cf1F9zLze9bW
should have the videos you're looking for.

**Comment by EvanBG42** [comment]
Looks like this is the video for the "doors that don't open task": https://youtu.be/hKpQZM5CpK8?list=PL497S23eeZrFvNm3dY3I3cf1F9zLze9bW

However, I can't find the video foe openable doors.

**Comment by EvanBG42** [comment]
Looks like this video mentions doors that open, but the title cards are somewhat misleading: https://youtu.be/8QwtiCidFR4
